name: matrix workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  example_matrix:
    runs-on: new-runner  
    strategy:
      matrix:
        loc: ["dir1", "dir2", "dir3", "dir4","dir5", "dir6", "dir7", "dir8", "dir9"]
    steps:
      - uses: actions/checkout@v2
      - name: Copy file to gcs bucket
        run: gsutil -m rsync -r helloworld.txt gs://demo-automate-hub-release/test/${{ matrix.loc }}/helloworld.txt
#         run: |
#           gsutil -m cp -r -n packages/ gs://demo-automate-hub-release/
#           gsutil cp categories.json gs://demo-automate-hub-release/categories.json
#           gsutil cp packages.json gs://demo-automate-hub-release/packages.json
